name: Tests

on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, windows-2016, ubuntu-18.04]
        version: [1.1.0, 1.0.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gh
      uses: ./
      with:
        version: ${{ matrix.version }}

    - run: gh --version
